-- =================================================================
-- INITIAL CLEANUP (FOR DEVELOPMENT ONLY - DO NOT RUN IN PRODUCTION)
-- =================================================================
-- DROP TABLE IF EXISTS escalation_logs, payments, subscriptions, messages, coaching_sessions, appointments, children, parents CASCADE;
-- DROP TYPE IF EXISTS mode_enum, subscription_status_enum, appointment_status_enum, coaching_session_status_enum, assessment_type_enum, urgency_level_enum, message_sender_enum, payment_type_enum, payment_status_enum, escalation_type_enum CASCADE;


-- =================================================================
-- TRIGGER FUNCTION FOR AUTOMATIC 'updated_at'
-- This single function will be used by all tables.
-- =================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- =================================================================
-- ENUM TYPE DEFINITIONS
-- =================================================================
CREATE TYPE mode_enum AS ENUM ('concierge', 'parenting_coach', 'awaiting_mode_selection', 'chat');
CREATE TYPE subscription_status_enum AS ENUM ('pre_trial', 'trialing', 'active_paid', 'trial_opted_out', 'trial_expired', 'cancelled');
CREATE TYPE appointment_status_enum AS ENUM ('pending_info', 'pending_payment', 'confirmed', 'completed', 'cancelled_by_parent', 'cancelled_by_clinic');
CREATE TYPE coaching_session_status_enum AS ENUM ('active', 'completed', 'abandoned');
CREATE TYPE follow_up_outcome_enum AS ENUM ('pending', 'succeeded', 'failed', 'not_applicable');
CREATE TYPE assessment_type_enum AS ENUM ('IQ/Giftedness', 'Depression/Anxiety/PTSD', 'ADHD', 'Autism Spectrum Disorder (ASD)', 'Global Developmental Delay', 'Intellectual Disability');
CREATE TYPE urgency_level_enum AS ENUM ('low', 'high');
CREATE TYPE message_sender_enum AS ENUM ('user', 'ai');
CREATE TYPE payment_type_enum AS ENUM ('appointment_fee', 'subscription');
CREATE TYPE payment_status_enum AS ENUM ('succeeded', 'pending', 'failed');
CREATE TYPE escalation_type_enum AS ENUM ('keyword_based', 'tone_based');


-- =================================================================
-- TABLE DEFINITIONS
-- =================================================================

CREATE TABLE parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whatsapp_id VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255),
    phone_number VARCHAR(50),
    email VARCHAR(255) UNIQUE,
    postal_code VARCHAR(20),
    is_wtw_employee BOOLEAN NOT NULL DEFAULT FALSE,

    -- Mode management
    current_mode mode_enum NOT NULL DEFAULT 'awaiting_mode_selection',
    current_step VARCHAR(255),

    -- Subscription management
    subscription_status subscription_status_enum NOT NULL DEFAULT 'pre_trial',
    trial_start_date TIMESTAMPTZ,
    session_count INT NOT NULL DEFAULT 0,
    stripe_customer_id VARCHAR(255) UNIQUE,

    -- Nudge management
    sent_nudge_day_7_soft_introduction BOOLEAN NOT NULL DEFAULT FALSE,
    sent_nudge_day_14_low_usage BOOLEAN NOT NULL DEFAULT FALSE,
    sent_nudge_day_20_conversion BOOLEAN NOT NULL DEFAULT FALSE,
    sent_nudge_day_28_final_reminder BOOLEAN NOT NULL DEFAULT FALSE,

    -- Monthly summary management
    monthly_summary_offered BOOLEAN NOT NULL DEFAULT FALSE,
    monthly_summary_opted_in BOOLEAN NOT NULL DEFAULT FALSE,
    monthly_summary_sent_at TIMESTAMPTZ,

    -- Common fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trigger_update_parents_updated_at BEFORE UPDATE ON parents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    name VARCHAR(255),
    date_of_birth DATE,

    -- Common fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trigger_update_children_updated_at BEFORE UPDATE ON children FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    child_id BIGINT REFERENCES children(id) ON DELETE SET NULL,
    status appointment_status_enum NOT NULL DEFAULT 'pending_info',
    assessment_type assessment_type_enum,
    preferred_time_slot TEXT,
    scheduled_datetime TIMESTAMPTZ,
    provider_assigned VARCHAR(255),
    case_notes TEXT,
    urgency_level urgency_level_enum NOT NULL DEFAULT 'low',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trigger_update_appointments_updated_at BEFORE UPDATE ON appointments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE coaching_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,

    -- Status management
    status coaching_session_status_enum NOT NULL DEFAULT 'active', -- ('active', 'completed', 'abandoned')

    session_start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    session_end_time TIMESTAMPTZ,

    parent_insight TEXT,
    action_step TEXT,

    follow_up_scheduled BOOLEAN NOT NULL DEFAULT FALSE,
    follow_up_sent_at TIMESTAMPTZ,

    -- Follow-up management
    follow_up_outcome follow_up_outcome_enum,
    follow_up_notes TEXT -- (Optional)
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    sender message_sender_enum NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE subscriptions (
    id SERIAL PRIMARY KEY,
    parent_id BIGINT UNIQUE NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL,
    stripe_subscription_id VARCHAR(255) UNIQUE NOT NULL,
    stripe_customer_id VARCHAR(255) NOT NULL, -- Direct lookup in Stripe.
    current_period_start TIMESTAMPTZ,
    current_period_end TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trigger_update_subscriptions_updated_at BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL,
    subscription_id BIGINT REFERENCES subscriptions(id) ON DELETE SET NULL,
    stripe_payment_intent_id VARCHAR(255) UNIQUE NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    payment_type payment_type_enum NOT NULL,
    payment_method VARCHAR(50),
    status payment_status_enum NOT NULL,
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trigger_update_payments_updated_at BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE escalation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    coaching_session_id BIGINT REFERENCES coaching_sessions(id) ON DELETE SET NULL,
    triggering_message TEXT,
    escalation_type escalation_type_enum NOT NULL,
    alert_sent_at TIMESTAMPTZ,
    is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =================================================================
-- NUDGE MANAGEMENT FUNCTIONS
-- =================================================================

CREATE OR REPLACE FUNCTION can_send_nudge_to_user(
    p_whatsapp_id VARCHAR(255),
    p_nudge_type VARCHAR(50)
) RETURNS BOOLEAN AS $$
DECLARE
    v_parent RECORD;
    v_days_since_trial_start INTEGER;
    v_session_count INTEGER;
    v_should_send BOOLEAN := FALSE;
BEGIN
    -- Get parent details
    SELECT 
        p.*,
        COALESCE(EXTRACT(DAY FROM (NOW() - p.trial_start_date)), 0)::INTEGER as trial_days
    INTO v_parent
    FROM parents p
    WHERE p.whatsapp_id = p_whatsapp_id;
    
    -- If parent not found or not in trial, don't send
    IF v_parent IS NULL OR v_parent.subscription_status != 'trialing' THEN
        RETURN FALSE;
    END IF;

    -- Get session count
    SELECT COUNT(*) INTO v_session_count 
    FROM coaching_sessions 
    WHERE parent_id = v_parent.id;

    -- Check nudge type and conditions
    CASE p_nudge_type
        WHEN 'day_7_soft_introduction' THEN
            -- Day 7: Soft Re-Introduction
            IF v_parent.trial_days >= 7 
               AND NOT v_parent.sent_nudge_day_7_soft_introduction 
               AND v_session_count <= 1 THEN
                v_should_send := TRUE;
            END IF;
            
        WHEN 'day_14_low_usage' THEN
            -- Day 14: Low Usage
            IF v_parent.trial_days >= 14 
               AND NOT v_parent.sent_nudge_day_14_low_usage 
               AND v_session_count <= 1 THEN
                v_should_send := TRUE;
            END IF;
            
        WHEN 'day_20_conversion' THEN
            -- Day 20: Conversion Prompt
            IF v_parent.trial_days >= 20 
               AND NOT v_parent.sent_nudge_day_20_conversion 
               AND v_session_count >= 2 
               AND v_parent.subscription_status = 'trialing' THEN
                v_should_send := TRUE;
            END IF;
            
        WHEN 'day_28_final_reminder' THEN
            -- Day 28: Final Reminder
            IF v_parent.trial_days >= 28 
               AND NOT v_parent.sent_nudge_day_28_final_reminder 
               AND v_parent.subscription_status = 'trialing' THEN
                v_should_send := TRUE;
            END IF;
            
        ELSE
            -- Unknown nudge type
            v_should_send := TRUE;
    END CASE;
    
    RETURN v_should_send;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =================================================================
-- MONTHLY REPORT FUNCTION
-- =================================================================

CREATE OR REPLACE FUNCTION create_monthly_report(
    p_whatsapp_id VARCHAR(255)
) RETURNS TEXT AS $$
DECLARE
    v_parent_id BIGINT;
    v_successful_follow_ups INTEGER;
    v_total_sessions INTEGER;
    v_report_text TEXT;
BEGIN
    -- Get parent ID
    SELECT id INTO v_parent_id 
    FROM parents 
    WHERE whatsapp_id = p_whatsapp_id;
    
    IF v_parent_id IS NULL THEN
        RETURN NULL;
    END IF;
    
    -- Count successful follow-ups in the last 30 days
    SELECT COUNT(*) INTO v_successful_follow_ups
    FROM coaching_sessions
    WHERE parent_id = v_parent_id
      AND follow_up_outcome = 'succeeded'
      AND session_end_time >= (NOW() - INTERVAL '30 days');
    
    -- Count total completed sessions in the last 30 days
    SELECT COUNT(*) INTO v_total_sessions
    FROM coaching_sessions
    WHERE parent_id = v_parent_id
      AND status = 'completed'
      AND session_end_time >= (NOW() - INTERVAL '30 days');
    
    -- Generate report text
    v_report_text := CONCAT(
        '📊 *Your Monthly Coaching Report* 📊\n\n',
        'Here is a summary of your coaching journey this month:\n\n',
        '✅ *Successful Follow-ups*: ', v_successful_follow_ups, '\n',
        '💬 *Total Coaching Sessions*: ', v_total_sessions, '\n\n',
        'Keep up the great work! If you have any questions or need support, feel free to reach out.'
    );
    
    -- Update the last report timestamp
    UPDATE parents 
    SET monthly_summary_sent_at = NOW()
    WHERE id = v_parent_id;
    
    RETURN v_report_text;
EXCEPTION
    WHEN OTHERS THEN
        -- Log the error and return NULL
        RAISE NOTICE 'Error generating monthly report: %', SQLERRM;
        RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =================================================================
-- INDEXES
-- =================================================================
CREATE INDEX IF NOT EXISTS idx_parents_whatsapp_id ON parents(whatsapp_id);
CREATE INDEX IF NOT EXISTS idx_parents_email ON parents(email);
CREATE INDEX IF NOT EXISTS idx_children_parent_id ON children(parent_id);
CREATE INDEX IF NOT EXISTS idx_appointments_parent_id ON appointments(parent_id);
CREATE INDEX IF NOT EXISTS idx_appointments_child_id ON appointments(child_id);
CREATE INDEX IF NOT EXISTS idx_coaching_sessions_parent_id ON coaching_sessions(parent_id);
CREATE INDEX IF NOT EXISTS idx_messages_parent_id ON messages(parent_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_parent_id ON subscriptions(parent_id);
CREATE INDEX IF NOT EXISTS idx_payments_parent_id ON payments(parent_id);
CREATE INDEX IF NOT EXISTS idx_payments_appointment_id ON payments(appointment_id);
CREATE INDEX IF NOT EXISTS idx_escalation_logs_parent_id ON escalation_logs(parent_id);