-- =================================================================
-- INITIAL CLEANUP (FOR DEVELOPMENT ONLY - DO NOT RUN IN PRODUCTION)
-- =================================================================
-- DROP TABLE IF EXISTS escalation_logs, payments, subscriptions, messages, coaching_sessions, appointments, children, parents CASCADE;
-- DROP TYPE IF EXISTS mode_enum, subscription_status_enum, appointment_status_enum, coaching_session_status_enum, assessment_type_enum, urgency_level_enum, message_sender_enum, payment_type_enum, payment_status_enum, escalation_type_enum CASCADE;


-- =================================================================
-- TRIGGER FUNCTION FOR AUTOMATIC 'updated_at'
-- This single function will be used by all tables.
-- =================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- =================================================================
-- ENUM TYPE DEFINITIONS
-- =================================================================
CREATE TYPE mode_enum AS ENUM ('concierge', 'parenting_coach', 'awaiting_mode_selection', 'chat');
CREATE TYPE subscription_status_enum AS ENUM ('pre_trial', 'trialing', 'active_paid', 'trial_opted_out', 'trial_expired', 'cancelled');
CREATE TYPE appointment_status_enum AS ENUM ('pending_info', 'pending_payment', 'confirmed', 'completed', 'cancelled_by_parent', 'cancelled_by_clinic');
CREATE TYPE coaching_session_status_enum AS ENUM ('active', 'completed', 'abandoned');
CREATE TYPE follow_up_outcome_enum AS ENUM ('pending', 'succeeded', 'failed', 'not_applicable');
CREATE TYPE assessment_type_enum AS ENUM ('IQ/Giftedness', 'Depression/Anxiety/PTSD', 'ADHD', 'Autism Spectrum Disorder (ASD)', 'Global Developmental Delay', 'Intellectual Disability');
CREATE TYPE urgency_level_enum AS ENUM ('low', 'high');
CREATE TYPE message_sender_enum AS ENUM ('user', 'ai');
CREATE TYPE payment_type_enum AS ENUM ('appointment_fee', 'subscription');
CREATE TYPE payment_status_enum AS ENUM ('succeeded', 'pending', 'failed');
CREATE TYPE escalation_type_enum AS ENUM ('keyword_based', 'tone_based');


-- =================================================================
-- TABLE DEFINITIONS
-- =================================================================

CREATE TABLE parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whatsapp_id VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255),
    phone_number VARCHAR(50),
    email VARCHAR(255) UNIQUE,
    postal_code VARCHAR(20),
    current_mode mode_enum NOT NULL DEFAULT 'awaiting_mode_selection',
    current_step VARCHAR(255),
    subscription_status subscription_status_enum NOT NULL DEFAULT 'pre_trial',
    trial_start_date TIMESTAMPTZ,
    trial_session_count INT NOT NULL DEFAULT 0,
    stripe_customer_id VARCHAR(255) UNIQUE,
    sent_nudge_day_7_soft_introduction BOOLEAN NOT NULL DEFAULT FALSE,
    sent_nudge_day_14_low_usage BOOLEAN NOT NULL DEFAULT FALSE,
    sent_nudge_day_20_conversion BOOLEAN NOT NULL DEFAULT FALSE,
    sent_nudge_day_28_reminder BOOLEAN NOT NULL DEFAULT FALSE,
    monthly_summary_offered BOOLEAN NOT NULL DEFAULT FALSE,
    monthly_summary_opted_in BOOLEAN NOT NULL DEFAULT FALSE,
    monthly_summary_sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trigger_update_parents_updated_at BEFORE UPDATE ON parents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    name VARCHAR(255),
    date_of_birth DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trigger_update_children_updated_at BEFORE UPDATE ON children FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    child_id BIGINT REFERENCES children(id) ON DELETE SET NULL,
    status appointment_status_enum NOT NULL DEFAULT 'pending_info',
    assessment_type assessment_type_enum,
    preferred_time_slot TEXT,
    scheduled_datetime TIMESTAMPTZ,
    provider_assigned VARCHAR(255),
    case_notes TEXT,
    urgency_level urgency_level_enum NOT NULL DEFAULT 'low',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trigger_update_appointments_updated_at BEFORE UPDATE ON appointments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE coaching_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,

    -- Cột này chỉ cho biết trạng thái của chính phiên coach
    status coaching_session_status_enum NOT NULL DEFAULT 'active', -- ('active', 'completed', 'abandoned')

    session_start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    session_end_time TIMESTAMPTZ,

    parent_insight TEXT,
    action_step TEXT,

    follow_up_scheduled BOOLEAN NOT NULL DEFAULT FALSE,
    follow_up_sent_at TIMESTAMPTZ,

    -- OPTIMIZATION: Thêm cột mới để lưu kết quả của hành động
    follow_up_outcome follow_up_outcome_enum,
    follow_up_notes TEXT -- (Tùy chọn) Để lưu chi tiết phản hồi của người dùng
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    sender message_sender_enum NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    -- OPTIMIZATION: Removed updated_at as messages are typically immutable.
);

CREATE TABLE subscriptions (
    id SERIAL PRIMARY KEY,
    -- OPTIMIZATION: Renamed table to be more specific.
    -- OPTIMIZATION: Added direct foreign key to parents table for data integrity.
    parent_id BIGINT UNIQUE NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    stripe_subscription_id VARCHAR(255) UNIQUE NOT NULL,
    stripe_customer_id VARCHAR(255) NOT NULL, -- Keep this for direct lookup in Stripe.
    status VARCHAR(50) NOT NULL,
    current_period_start TIMESTAMPTZ, -- OPTIMIZATION: Changed to TIMESTAMPTZ for consistency
    current_period_end TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trigger_update_subscriptions_updated_at BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL,
    subscription_id BIGINT REFERENCES subscriptions(id) ON DELETE SET NULL, -- OPTIMIZATION: Added link to subscription
    stripe_payment_intent_id VARCHAR(255) UNIQUE NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    payment_type payment_type_enum NOT NULL,
    payment_method VARCHAR(50),
    status payment_status_enum NOT NULL,
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    -- OPTIMIZATION: Removed redundant customer info. Use JOIN on parents table to get it.
);
CREATE TRIGGER trigger_update_payments_updated_at BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE escalation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    coaching_session_id BIGINT REFERENCES coaching_sessions(id) ON DELETE SET NULL,
    triggering_message TEXT,
    escalation_type escalation_type_enum NOT NULL,
    alert_sent_at TIMESTAMPTZ,
    is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =================================================================
-- INDEXES (largely the same, very well-defined)
-- =================================================================
CREATE INDEX IF NOT EXISTS idx_parents_whatsapp_id ON parents(whatsapp_id);
CREATE INDEX IF NOT EXISTS idx_parents_email ON parents(email);
CREATE INDEX IF NOT EXISTS idx_children_parent_id ON children(parent_id);
CREATE INDEX IF NOT EXISTS idx_appointments_parent_id ON appointments(parent_id);
CREATE INDEX IF NOT EXISTS idx_appointments_child_id ON appointments(child_id);
CREATE INDEX IF NOT EXISTS idx_coaching_sessions_parent_id ON coaching_sessions(parent_id);
CREATE INDEX IF NOT EXISTS idx_messages_parent_id ON messages(parent_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_parent_id ON subscriptions(parent_id);
CREATE INDEX IF NOT EXISTS idx_payments_parent_id ON payments(parent_id);
CREATE INDEX IF NOT EXISTS idx_payments_appointment_id ON payments(appointment_id);
CREATE INDEX IF NOT EXISTS idx_escalation_logs_parent_id ON escalation_logs(parent_id);