-- =================================================================
-- PARENTING SUPPORT PLATFORM - DATABASE SCHEMA
-- =================================================================
-- This schema supports a multi-modal parenting platform with:
-- - Concierge services for appointments
-- - AI coaching sessions
-- - Subscription management
-- - Payment processing
-- - Communication tracking
-- =================================================================

-- =================================================================
-- DEVELOPMENT CLEANUP (UNCOMMENT FOR DEV ENVIRONMENT ONLY)
-- =================================================================
-- WARNING: These commands will delete all data - use only in development!
-- DROP TABLE IF EXISTS escalation_logs, payments, subscriptions, messages, coaching_sessions, appointments, children, parents, voice_calls, subscription_plans CASCADE;
-- DROP TYPE IF EXISTS mode_enum, subscription_status_enum, subscription_type_enum, appointment_status_enum, coaching_session_status_enum, assessment_type_enum, urgency_level_enum, message_sender_enum, payment_status_enum, escalation_type_enum, user_preferred_language_enum, follow_up_outcome_enum CASCADE;

-- =================================================================
-- UTILITY FUNCTIONS
-- =================================================================

-- Universal trigger function for updating 'updated_at' timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =================================================================
-- ENUM DEFINITIONS
-- =================================================================

-- Platform interaction modes
CREATE TYPE mode_enum AS ENUM (
    'concierge',                -- Appointment booking assistance
    'parenting_coach',          -- AI coaching sessions
    'awaiting_mode_selection',  -- Initial state
    'chat'                      -- General chat mode
);

-- Subscription lifecycle states
CREATE TYPE subscription_status_enum AS ENUM (
    'pre_trial',        -- Before trial starts
    'trialing',         -- Active trial period
    'active_paid',      -- Paying subscriber
    'trial_opted_out',  -- User declined trial
    'trial_expired',    -- Trial ended without conversion
    'cancelled'         -- Subscription cancelled
);

-- Subscription billing cycles
CREATE TYPE subscription_type_enum AS ENUM (
    'monthly',
    'yearly'
);

-- Appointment workflow states
CREATE TYPE appointment_status_enum AS ENUM (
    'pending_info',         -- Waiting for user information
    'pending_payment',      -- Waiting for payment
    'confirmed',           -- Appointment confirmed
    'completed',           -- Service delivered
    'cancelled_by_parent', -- User cancelled
    'cancelled_by_clinic'  -- Provider cancelled
);

-- Coaching session states
CREATE TYPE coaching_session_status_enum AS ENUM (
    'active',     -- Session ongoing
    'completed',  -- Session finished normally
    'abandoned'   -- Session ended prematurely
);

-- Follow-up tracking
CREATE TYPE follow_up_outcome_enum AS ENUM (
    'pending',         -- Follow-up scheduled but not sent
    'succeeded',       -- Follow-up sent successfully
    'failed',          -- Follow-up failed to send
    'not_applicable'   -- No follow-up needed
);

-- Clinical assessment categories
CREATE TYPE assessment_type_enum AS ENUM (
    'IQ/Giftedness',
    'Depression/Anxiety/PTSD',
    'ADHD',
    'Autism Spectrum Disorder (ASD)',
    'Global Developmental Delay',
    'Intellectual Disability'
);

-- Priority levels
CREATE TYPE urgency_level_enum AS ENUM (
    'low',
    'high'
);

-- Message attribution
CREATE TYPE message_sender_enum AS ENUM (
    'user',  -- Parent/user message
    'ai'     -- System/AI response
);

-- Message type
CREATE TYPE message_type_enum AS ENUM (
    'whatsapp',  -- WhatsApp message
    'call'       -- Phone call
);

-- Payment processing states
CREATE TYPE payment_status_enum AS ENUM (
    'succeeded',  -- Payment completed
    'pending',    -- Payment processing
    'failed'      -- Payment failed
);

-- Alert trigger types
CREATE TYPE escalation_type_enum AS ENUM (
    'keyword_based',  -- Triggered by specific keywords
    'tone_based'      -- Triggered by sentiment analysis
);

-- User language preferences
CREATE TYPE user_preferred_language_enum AS ENUM (
    'english',
    'chinese'
);

-- =================================================================
-- CORE TABLES
-- =================================================================

-- Parent/User Management
-- Stores primary user accounts and their platform state
CREATE TABLE parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Identity & Contact
    whatsapp_id VARCHAR(255) UNIQUE NOT NULL,    -- Primary identifier from WhatsApp
    full_name VARCHAR(255),
    phone_number VARCHAR(50),
    email VARCHAR(255) UNIQUE,
    postal_code VARCHAR(20),
    is_wtw_employee BOOLEAN NOT NULL DEFAULT FALSE,  -- Internal staff flag
    
    -- Platform State Management
    current_mode mode_enum NOT NULL DEFAULT 'awaiting_mode_selection',
    current_step VARCHAR(255),                    -- Current step in conversation flow
    
    -- Subscription Management
    subscription_status subscription_status_enum NOT NULL DEFAULT 'pre_trial',
    trial_start_date TIMESTAMPTZ,
    session_count INT NOT NULL DEFAULT 0,        -- Total coaching sessions count
    stripe_customer_id VARCHAR(255) UNIQUE,      -- Stripe customer reference
    
    -- Communication Management
    follow_up_sent_at TIMESTAMPTZ,               -- Last follow-up timestamp
    sent_trial_expiry BOOLEAN NOT NULL DEFAULT FALSE,  -- Trial expiry notification flag
    monthly_summary_sent_at TIMESTAMPTZ,         -- Last monthly report timestamp
    
    -- Audit Trail
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Child Information
-- Stores information about children for appointment booking
CREATE TABLE children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL,                    -- Reference to parent (FK defined below)
    
    -- Child Details
    name VARCHAR(255),
    date_of_birth DATE,
    
    -- Audit Trail
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Appointment Management
-- Tracks concierge service appointments from inquiry to completion
CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL,                    -- Reference to parent (FK defined below)
    child_id BIGINT,                              -- Reference to child (FK defined below)
    
    -- Appointment Details
    status appointment_status_enum NOT NULL DEFAULT 'pending_info',
    assessment_type assessment_type_enum,
    preferred_time_slot TEXT,                     -- User's preferred timing
    scheduled_datetime TIMESTAMPTZ,               -- Confirmed appointment time
    provider_assigned VARCHAR(255),               -- Healthcare provider name
    case_notes TEXT,                              -- Internal notes
    urgency_level urgency_level_enum NOT NULL DEFAULT 'low',
    
    -- Audit Trail
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Coaching Session Management
-- Tracks AI coaching conversations and outcomes
CREATE TABLE coaching_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL,                    -- Reference to parent (FK defined below)
    
    -- Session Lifecycle
    status coaching_session_status_enum NOT NULL DEFAULT 'active',
    session_start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    session_end_time TIMESTAMPTZ,
    
    -- Session Outcomes
    parent_insight TEXT,                          -- Key insight from session
    action_step TEXT,                             -- Recommended next step
    
    -- Follow-up Management
    follow_up_scheduled BOOLEAN NOT NULL DEFAULT FALSE,
    follow_up_sent_at TIMESTAMPTZ,
    follow_up_outcome follow_up_outcome_enum,
    follow_up_notes TEXT                          -- Optional follow-up details
);

-- Message History
-- Stores all communication between users and the platform
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL,                    -- Reference to parent (FK defined below)
    
    -- Message Content
    sender message_sender_enum NOT NULL,
    content TEXT NOT NULL,
    message_type message_type_enum NOT NULL DEFAULT 'whatsapp',
    
    -- Audit Trail
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Subscription Plans
-- Defines available subscription tiers and pricing
CREATE TABLE subscription_plans (
    id SERIAL PRIMARY KEY,
    
    -- Stripe Integration
    stripe_price_id VARCHAR(255) UNIQUE NOT NULL, -- Stripe Price ID (not Product ID)
    
    -- Plan Details
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type subscription_type_enum NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'SGD',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,      -- Plan availability flag
    
    -- Audit Trail
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Active Subscriptions
-- Tracks user subscription states and billing cycles
CREATE TABLE subscriptions (
    id SERIAL PRIMARY KEY,
    
    -- Subscription State
    stripe_status VARCHAR(50),
    stripe_subscription_id VARCHAR(255) UNIQUE NOT NULL,
    stripe_customer_id VARCHAR(255) NOT NULL,
    customer_email VARCHAR(50),
    
    -- Billing Cycle
    current_period_start TIMESTAMPTZ,
    current_period_end TIMESTAMPTZ,
    cancel_at_period_end BOOLEAN DEFAULT FALSE,
    
    -- Audit Trail
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Payment Records
-- Tracks all financial transactions
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL,                    -- Reference to parent (FK defined below)
    plan_id BIGINT NOT NULL,                      -- Reference to plan (FK defined below)
    subscription_id BIGINT NOT NULL,              -- Reference to subscription (FK defined below)
    
    -- Payment Details
    stripe_invoice_id VARCHAR(255),
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    payment_method VARCHAR(50),
    
    -- Payment State
    status payment_status_enum NOT NULL,
    failure_reason TEXT,
    
    -- Audit Trail
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Escalation Tracking
-- Logs situations requiring human intervention
CREATE TABLE escalation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL,                    -- Reference to parent (FK defined below)
    coaching_session_id BIGINT,                   -- Reference to session (FK defined below)
    
    -- Escalation Details
    triggering_message TEXT,                      -- Message that triggered escalation
    escalation_type escalation_type_enum NOT NULL,
    alert_sent_at TIMESTAMPTZ,
    is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Audit Trail
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Voice Call Management
-- Tracks voice communication sessions
CREATE TABLE voice_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL,                    -- Reference to parent (FK defined below)
    
    -- Call Details
    call_sid VARCHAR(255),                        -- Twilio call identifier
    stream_sid VARCHAR(255),                      -- Twilio stream identifier
    target_phone VARCHAR(50),
    status VARCHAR(50) NOT NULL,
    user_preferred_language user_preferred_language_enum NOT NULL,
    
    -- Call Lifecycle
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    disconnected_at TIMESTAMPTZ
);

-- =================================================================
-- FOREIGN KEY CONSTRAINTS
-- =================================================================

-- Child → Parent relationship
ALTER TABLE children 
    ADD CONSTRAINT fk_children_parent 
    FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE CASCADE;

-- Appointment relationships
ALTER TABLE appointments 
    ADD CONSTRAINT fk_appointments_parent 
    FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE CASCADE;

ALTER TABLE appointments 
    ADD CONSTRAINT fk_appointments_child 
    FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE SET NULL;

-- Coaching session → Parent relationship
ALTER TABLE coaching_sessions 
    ADD CONSTRAINT fk_coaching_sessions_parent 
    FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE CASCADE;

-- Message → Parent relationship
ALTER TABLE messages 
    ADD CONSTRAINT fk_messages_parent 
    FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE CASCADE;

-- Subscription relationships
ALTER TABLE subscriptions 
    ADD CONSTRAINT fk_subscriptions_parent 
    FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE CASCADE;

ALTER TABLE subscriptions 
    ADD CONSTRAINT fk_subscriptions_plan 
    FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plans(id);

-- Payment relationships
ALTER TABLE payments 
    ADD CONSTRAINT fk_payments_parent 
    FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE CASCADE;

ALTER TABLE payments 
    ADD CONSTRAINT fk_payments_plan 
    FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE SET NULL;

ALTER TABLE payments 
    ADD CONSTRAINT fk_payments_subscription 
    FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL;

-- Escalation relationships
ALTER TABLE escalation_logs 
    ADD CONSTRAINT fk_escalation_logs_parent 
    FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE CASCADE;

ALTER TABLE escalation_logs 
    ADD CONSTRAINT fk_escalation_logs_session 
    FOREIGN KEY (coaching_session_id) REFERENCES coaching_sessions(id) ON DELETE SET NULL;

-- Voice call → Parent relationship
ALTER TABLE voice_calls 
    ADD CONSTRAINT fk_voice_calls_parent 
    FOREIGN KEY (parent_id) REFERENCES parents(id) ON DELETE CASCADE;

-- =================================================================
-- UNIQUE CONSTRAINTS
-- =================================================================

-- Ensure one active subscription per parent
ALTER TABLE subscriptions 
    ADD CONSTRAINT unique_parent_subscription 
    UNIQUE (parent_id);

-- =================================================================
-- DATABASE TRIGGERS
-- =================================================================

-- Auto-update timestamps on record modification
CREATE TRIGGER trigger_update_parents_updated_at 
    BEFORE UPDATE ON parents 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_update_children_updated_at 
    BEFORE UPDATE ON children 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_update_appointments_updated_at 
    BEFORE UPDATE ON appointments 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_update_subscription_plans_updated_at 
    BEFORE UPDATE ON subscription_plans 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_update_subscriptions_updated_at 
    BEFORE UPDATE ON subscriptions 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_update_payments_updated_at 
    BEFORE UPDATE ON payments 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =================================================================
-- DATABASE INDEXES
-- =================================================================

-- Primary lookup indexes
CREATE INDEX IF NOT EXISTS idx_parents_whatsapp_id ON parents(whatsapp_id);
CREATE INDEX IF NOT EXISTS idx_parents_email ON parents(email);

-- Foreign key indexes for performance
CREATE INDEX IF NOT EXISTS idx_children_parent_id ON children(parent_id);
CREATE INDEX IF NOT EXISTS idx_appointments_parent_id ON appointments(parent_id);
CREATE INDEX IF NOT EXISTS idx_appointments_child_id ON appointments(child_id);
CREATE INDEX IF NOT EXISTS idx_coaching_sessions_parent_id ON coaching_sessions(parent_id);
CREATE INDEX IF NOT EXISTS idx_messages_parent_id ON messages(parent_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_parent_id ON subscriptions(parent_id);
CREATE INDEX IF NOT EXISTS idx_payments_parent_id ON payments(parent_id);
CREATE INDEX IF NOT EXISTS idx_escalation_logs_parent_id ON escalation_logs(parent_id);
CREATE INDEX IF NOT EXISTS idx_voice_calls_parent_id ON voice_calls(parent_id);

-- =================================================================
-- BUSINESS LOGIC FUNCTIONS
-- =================================================================

-- Nudge Management: Determines if a user should receive promotional messages
CREATE OR REPLACE FUNCTION can_send_nudge_to_user(
    p_whatsapp_id VARCHAR(255),
    p_nudge_type VARCHAR(50)
) RETURNS BOOLEAN AS $$
DECLARE
    v_parent RECORD;
    v_days_since_trial_start INTEGER;
    v_session_count INTEGER;
    v_should_send BOOLEAN := FALSE;
BEGIN
    -- Retrieve parent details with trial duration
    SELECT 
        p.*,
        COALESCE(EXTRACT(DAY FROM (NOW() - p.trial_start_date)), 0)::INTEGER as trial_days
    INTO v_parent
    FROM parents p
    WHERE p.whatsapp_id = p_whatsapp_id;
    
    -- Validate parent exists and is in trial
    IF v_parent IS NULL OR v_parent.subscription_status != 'trialing' THEN
        RETURN FALSE;
    END IF;

    -- Count completed coaching sessions
    SELECT COUNT(*) INTO v_session_count 
    FROM coaching_sessions 
    WHERE parent_id = v_parent.id;

    -- Apply nudge-specific business rules
    CASE p_nudge_type
        WHEN 'trial_expiry' THEN
            -- Send trial expiry reminder after 7 days, once per trial
            IF v_parent.trial_days >= 7 
               AND NOT v_parent.sent_trial_expiry 
               AND v_parent.subscription_status = 'trialing' THEN
                v_should_send := TRUE;
            END IF;
            
        ELSE
            -- Unknown nudge type - default to no send
            v_should_send := FALSE;
    END CASE;
    
    RETURN v_should_send;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Monthly Reporting: Checks eligibility for monthly summary reports
CREATE OR REPLACE FUNCTION can_send_monthly_summary_to_user(
    p_whatsapp_id VARCHAR(255)
) RETURNS BOOLEAN AS $$
DECLARE
    v_parent_id BIGINT;
BEGIN
    -- Find parent by WhatsApp ID
    SELECT id INTO v_parent_id 
    FROM parents 
    WHERE whatsapp_id = p_whatsapp_id;
    
    IF v_parent_id IS NULL THEN
        RETURN FALSE;
    END IF;
    
    -- Check if user is eligible (trial or paid subscriber)
    IF EXISTS (
        SELECT 1
        FROM parents
        WHERE id = v_parent_id
          AND (subscription_status = 'trialing' OR subscription_status = 'active_paid')
    ) THEN
        RETURN TRUE;
    END IF;
    
    RETURN FALSE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Monthly Report Generation: Creates summary statistics for user engagement
CREATE OR REPLACE FUNCTION create_monthly_summary_for_user(
    p_whatsapp_id VARCHAR(255)
) RETURNS TABLE (
    parent_full_name VARCHAR(255),
    successful_follow_ups INTEGER,
    total_sessions INTEGER
) AS $$
BEGIN
    RETURN QUERY
    WITH parent_info AS (
        SELECT id, full_name 
        FROM parents 
        WHERE whatsapp_id = p_whatsapp_id
    ),
    follow_ups AS (
        SELECT COUNT(*) as count
        FROM coaching_sessions
        WHERE parent_id = (SELECT id FROM parent_info)
          AND follow_up_outcome = 'succeeded'
          AND session_end_time >= (NOW() - INTERVAL '30 days')
    ),
    sessions AS (
        SELECT COUNT(*) as count
        FROM coaching_sessions
        WHERE parent_id = (SELECT id FROM parent_info)
          AND status = 'completed'
          AND session_end_time >= (NOW() - INTERVAL '30 days')
    )
    SELECT 
        p.full_name::VARCHAR(255),
        COALESCE(f.count, 0)::INTEGER,
        COALESCE(s.count, 0)::INTEGER
    FROM 
        parent_info p
        CROSS JOIN LATERAL (SELECT count FROM follow_ups) f
        CROSS JOIN LATERAL (SELECT count FROM sessions) s;
EXCEPTION
    WHEN OTHERS THEN
        -- Log error and return safe defaults
        RAISE NOTICE 'Error generating monthly report for %: %', p_whatsapp_id, SQLERRM;
        RETURN QUERY SELECT NULL::VARCHAR(255), NULL::INTEGER, NULL::INTEGER;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
